export const QUERY_KEYS = {
  ADMIN_RENTS: "adminRents",
  ADMIN_LOCATION: "adminLocation",
  ADMIN_CATEGORIES: "adminCategories",
  ADMIN_RESERVATIONS: "adminReservations",
  RENT_DETAIL_REVIEW: "rentDetailReview",
  ADMIN_REVIEWS: "adminReviews",
  ADMIN_RENT_DETAIL: "adminRentDetail",
  ADMIN_RENT_BY_ID: "admin-rent-by-id",
  ADMIN_LOCATION_BY_ID: "admin-location-by-id",
  ADMIN_CATEGORY_BY_ID: "admin-category-by-id",
  CATEGORIES: "categories",
  LOCATIONS: "locations",
  RESERVATIONS: "reservations",
  RECOMMENDATION_RENTS: "recommendationRents",
  RENT_LIST: "rentList",
  RENT_DETAIL: "rentDetail",
  USER_CONVERSATION: "userConversation",
  ADMIN_CHAT: "adminChat",
  ADMIN_CONVERSATIONS: "adminConversations",
  POPULAR_RENTS: "popularRents",
};
